#cloud-config
package_update: true
package_upgrade: true
packages:
    - python3-apt
    - python3-pip
    - build-essential
    - unzip
    - curl
    - jq
    - git
snap:
    commands:
      00: snap install yq
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}
power_state:
  delay: "60"
  mode: reboot
  condition: True